### ISSUE TITLE
No ability to set sender name and email

### ISSUE THREAD

**Issue by marvc1** [Mimeo/SendWithUs.Client#8]
Hello,

Thanks for open sourcing this project. The sender name and email are not set when using it though. This means that I cannot use an alias when sending emails through this project.

Dylan at SendWithUs Support confirms and says the issue is with this class https://github.com/Mimeo/SendWithUs.Client/blob/master/SendWithUs.Client/Requests/SendRequestConverter.cs#L33

Is anyone at mimeo able to fix it, or are you willing to take a pr?

**Comment by marvc1** [comment]
Specifically, in code this is it:

'var request = new SendRequest
            {
                TemplateId = "templateId",
                SenderName = "From my sender",
                SenderAddress = "sender@example.com",
                SenderReplyTo = "sender@example.com",
                RecipientAddress = "recipient@example.com"
            };

var client = new SendWithUsClient(_apiKey);
client.SendAsync(request);'

The SenderName, SenderAddress & SenderReplyTo property's are not passed correct to the SendWithUs api

**Comment by drub0y** [comment]
Thanks for reporting this! We'll take a look when we have some spare cycles. We would gladly accept a PR if you want to take a stab at fixing it before then!

**Comment by lencharest** [comment]
Holy cow! It looks like we have *never* serialized the sender info from the request.

**Comment by lencharest** [comment]
Fix merged into master branch. New package available on nuget.org at https://www.nuget.org/packages/SendWithUs.Client/0.4.1.
